// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9QFFoAGEt_JYaavmBy_G7_8mnuPA6inQ',
    appId: '1:720431863335:web:2c6ca84edb4c2ef1a86002',
    messagingSenderId: '720431863335',
    projectId: 'fresh-iridium-388814',
    authDomain: 'fresh-iridium-388814.firebaseapp.com',
    storageBucket: 'fresh-iridium-388814.appspot.com',
    measurementId: 'G-JYZ8P6RYC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZOgkmM0uP_Gf2e8_-VJAOhCbVvkrmF8',
    appId: '1:720431863335:android:c3b93c5f375c9895a86002',
    messagingSenderId: '720431863335',
    projectId: 'fresh-iridium-388814',
    storageBucket: 'fresh-iridium-388814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDppPund196PgDPhCc5VRzyN8GeuUQvKxM',
    appId: '1:720431863335:ios:8c76a25aeb4ae4eda86002',
    messagingSenderId: '720431863335',
    projectId: 'fresh-iridium-388814',
    storageBucket: 'fresh-iridium-388814.appspot.com',
    iosClientId: '720431863335-3fs6pc87jbjurpq4geon72msf7js1idn.apps.googleusercontent.com',
    iosBundleId: 'com.example.atv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDppPund196PgDPhCc5VRzyN8GeuUQvKxM',
    appId: '1:720431863335:ios:f8684dba67f544b3a86002',
    messagingSenderId: '720431863335',
    projectId: 'fresh-iridium-388814',
    storageBucket: 'fresh-iridium-388814.appspot.com',
    iosClientId: '720431863335-sn6g3gog269nucs1r6s5kp48hqckn5q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.atv1.RunnerTests',
  );
}
